version: "3.9"
services:
  postgres:
    container_name: leet_clone_postgres   
    image: postgres:13.3
    environment:
      POSTGRES_DB: "leet_clone"
      POSTGRES_USER: "otus"
      POSTGRES_PASSWORD: "202312"
      PGDATA: "/var/lib/postgresql/data/pgdata"      
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data            
    ports:
    - "5432:5432"
  api:
    image: leet-clone-app
    build:
      dockerfile: ../Dockerfile
    ports:
    - "3000:3000"
    depends_on:
      - postgres                    